<p>Erro durante a sincronização de provedores de relatórios <a
        href="/instâncias/{{$instance_id}}"><strong>{{ $instance_name }}</strong></a> falhou.
    Mensagem:{{ $exception_message }}</p>
